
:- ensure_loaded('./applicability.pl').
:- ensure_loaded('./graph_debug.pl').

node_cost(node(_, _, _, Cost, _, _), Cost).

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%* Insert node keeping OPEN sorted by ascending cost. Stable for equal costs.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
insert_open_by_cost(Node, [], [Node]).
insert_open_by_cost(Node, [Head | Tail], [Node, Head | Tail]) :-
  node_cost(Node, Cost),
  node_cost(Head, HeadCost),
  Cost < HeadCost,
  !.
insert_open_by_cost(Node, [Head | Tail], [Head | Rest]) :-
  insert_open_by_cost(Node, Tail, Rest).


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%* Retrieves a node with a given state from a list of nodes. Returns the first match. Fails if no 
%  match is found. CurrentState and State in node/6 must be lists of literals.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
get_state_from_list(CurrentState, [node(State, PrevState, ActionName, Cost, Depth, Invariants)|_], node(State, PrevState, ActionName, Cost, Depth, Invariants)) :- 
  equal_lists(CurrentState, State), !.
get_state_from_list(CurrentState, [_|Tail], Node) :-
  get_state_from_list(CurrentState, Tail, Node).


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%! Processes a candidate successor state by updating cost/depth, skipping states already in CLOSE, 
%  replacing worse duplicates in OPEN, or inserting a new node into OPEN in cost order.
%  @param CurrentNode The node being expanded, used for debugging and to compute the new cost/depth.
%  @param NewState The new state generated by applying an action to CurrentState from CurrentNode.
%  @param NewInvariants The list of invariants for the new state to be stored in the new node.
%  @param StepLabel A label for the edge from CurrentState to NewState (end(ActionName) or start(ActionName)).
%  @param OPEN0 The current OPEN list, used to check for duplicates and to insert the new node if needed.
%  @param CLOSE The current CLOSE list, used to check for duplicates.
%  @param OPEN1 The updated OPEN list after processing the new state, which will be returned.

%  @detailed This checks if NewState is the state of any node of CLOSE. If so, it skips it and 
%  leaves OPEN unchanged. Otherwise, it computes NewCost and NewDepth by incrementing Cost and Depth 
%  from CurrentNode. Then, it checks if NewState is the state of any node of OPEN. If so, it 
%  compares NewCost with OldCost from the existing node. If NewCost is lower, it replaces the 
%  existing node with a new node created with NewState, CurrentState, StepLabel, NewCost, NewDepth,
%  and NewInvariants, inserting it into OPEN in cost order. If NewCost is not lower, it skips the 
%  new state and leaves OPEN unchanged. If NewState is not found in OPEN, it creates a new node
%  with NewState, CurrentState, StepLabel, NewCost, NewDepth, and NewInvariants, and inserts it into 
%  OPEN in cost order.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
maybe_enqueue_successor(
    node(CurrentState, _Prev, _ActionToCurrentState, CurrentCost, CurrentDepth, _Invs),
    NewState,
    NewInvariants,
    StepLabel,
    OPEN0,
    CLOSE,
    OPEN1
) :-
  (
    StepLabel = end(ActionName);
    StepLabel = start(ActionName)
  ),
  hl_d_action(ActionName, PredicatesStart, PredicatesEnd, Overall, EffectsStart, EffectsEnd, Duration),
  ( 
    once(get_state_from_list(NewState, CLOSE, _)) 
    ->(
      NewCost  is CurrentCost + 1,
      NewDepth is CurrentDepth + 1,
      graph_emit_edge(CurrentState, NewState, StepLabel, skipped_close, NewDepth, NewCost, []),
      OPEN1 = OPEN0
    );(
      NewCost  is CurrentCost + 1,
      NewDepth is CurrentDepth + 1,
      NewNode  = node(NewState, CurrentState, StepLabel, NewCost, NewDepth, NewInvariants),
      (
        % Match duplicates by logical state (order-insensitive), not by exact list order.
        once(get_state_from_list(NewState, OPEN0, ExistingNode))
        ->(
          ExistingNode = node(_ExistingState, _OldPrevState, _OldAction, OldCost, _OldDepth, _OldInvs),
          NewCost < OldCost
          ->(
              graph_emit_edge(CurrentState, NewState, StepLabel, replaced_open, NewDepth, NewCost, [ActionName, PredicatesStart, PredicatesEnd, Overall, EffectsStart, EffectsEnd, Duration]),
              select(ExistingNode, OPEN0, Rest),
              insert_open_by_cost(NewNode, Rest, OPEN1)
          );(
              graph_emit_edge(CurrentState, NewState, StepLabel, skipped_open_better, NewDepth, NewCost, []),
              OPEN1 = OPEN0
          )
        );(
          graph_emit_edge(CurrentState, NewState, StepLabel, enqueued, NewDepth, NewCost, [ActionName, PredicatesStart, PredicatesEnd, Overall, EffectsStart, EffectsEnd, Duration]),
          insert_open_by_cost(NewNode, OPEN0, OPEN1)
        )
      )
    )
  ).

% Phase-specific loop: START
generate_states_start(_Node, [], OPEN, _CLOSE, OPEN).
generate_states_start(
  node(CurrentState, PrevState, OldAction, Cost, Depth, Invs),
  [hl_d_action(ActionName, _, _, _, EffectsStart, _, _) | TActions],
  OPEN0, 
  CLOSE, 
  OPENF
) :-
  apply_effects(EffectsStart, CurrentState, TmpState),
  NewState = [executing(ActionName) | TmpState],
  executing_invariants(NewState, NewInvariants),
  maybe_enqueue_successor(node(CurrentState, PrevState, OldAction, Cost, Depth, Invs), NewState, NewInvariants, start(ActionName), OPEN0, CLOSE, OPEN1),
  generate_states_start(node(CurrentState, PrevState, OldAction, Cost, Depth, Invs), TActions, OPEN1, CLOSE, OPENF).


% Phase-specific loop: END
generate_states_end(_Node, [], OPEN, _CLOSE, OPEN).
generate_states_end(
  node(CurrentState, PrevState, OldAction, Cost, Depth, Invs),
  [hl_d_action(ActionName, _, _, _, _, EffectsEnd, _) | TActions],
  OPEN0, 
  CLOSE, 
  OPENF
) :-
  apply_effects(EffectsEnd, CurrentState, TmpState),
  select(executing(ActionName), TmpState, NewState),
  executing_invariants(NewState, NewInvariants),
  maybe_enqueue_successor(node(CurrentState, PrevState, OldAction, Cost, Depth, Invs),
                         NewState, NewInvariants, end(ActionName),
                         OPEN0, CLOSE, OPEN1),
  generate_states_end(node(CurrentState, PrevState, OldAction, Cost, Depth, Invs), TActions, OPEN1, CLOSE, OPENF).





